# 0/1 Knapsack problem

Referenced an explanation by Tushar Roy: <br>
https://www.youtube.com/watch?v=8LusJS5-AGo&list=PLrmLmBdmIlpsHaNTPP_jHHDx_os9ItYXr&index=2

In [1]:
import numpy as np

n_items = 4
values = [1,4,5,7]
weights = [1,3,4,5]
items = list(zip(weights, values))
weight_limit = 7

T = [[0] * (weight_limit+1) for _ in range(n_items)]
    
print(np.array(T))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [2]:
for curr_limit in range(weight_limit + 1):
    if weights[0] <= curr_limit:
        T[0][curr_limit] = values[0]

print(np.array(T))

[[0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [3]:
for r in range(1,n_items):
    for c in range(1, weight_limit + 1):
        add = values[r] + T[r-1][c - weights[r]] if c >= weights[r] else 0
        or_not = T[r-1][c]
        T[r][c] = max(add, or_not)
    
print(np.array(T))

[[0 1 1 1 1 1 1 1]
 [0 1 1 4 5 5 5 5]
 [0 1 1 4 5 6 6 9]
 [0 1 1 4 5 7 8 9]]
